// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AndroidGPGSIds
{
        public const string achievement_play_void_light = "CgkIobGfs60UEAIQBg"; // <GPGSID>
        public const string achievement_bookworm = "CgkIobGfs60UEAIQCg"; // <GPGSID>
        public const string achievement_across_the_void = "CgkIobGfs60UEAIQAQ"; // <GPGSID>
        public const string achievement_light_it_up = "CgkIobGfs60UEAIQBA"; // <GPGSID>
        public const string achievement_a_new_look = "CgkIobGfs60UEAIQBQ"; // <GPGSID>
        public const string achievement_goodies = "CgkIobGfs60UEAIQCQ"; // <GPGSID>
        public const string achievement_the_calling = "CgkIobGfs60UEAIQCA"; // <GPGSID>
        public const string achievement_chasing_light = "CgkIobGfs60UEAIQAw"; // <GPGSID>
        public const string achievement_no_longer_the_lost = "CgkIobGfs60UEAIQAA"; // <GPGSID>
        public const string leaderboard_high_streak = "CgkIobGfs60UEAIQBw"; // <GPGSID>
        public const string achievement_evading_darkness = "CgkIobGfs60UEAIQAg"; // <GPGSID>

}

